# Funciones aleatorias

Hablando de funciones no podemos olvidar las funciones aleatorias encontradas en el módulo `random`. [En la documentación oficial](https://numpy.org/doc/stable/reference/random/index.html) encontraréis el listado completo con ejemplos de uso.

Tenemos funciones para generar arrays con `datos aleatorios` y `permutaciones`. También hay muchas enfocadas a generar muestras de distribuciones de probabilidad pensadas para visualizar estadística.

Vamos a practicar algunas de las dos primeras.

## Datos aleatorios

In [2]:
import numpy as np

In [5]:
# número decimal entre 0 y 1
np.random.rand()

0.6272146499160006

In [7]:
# array 1D de decimales entre 0 y 1
np.random.rand(4)

array([0.23708799, 0.7931136 , 0.95160495, 0.10282471])

In [12]:
# array 2D de decimales entre 0 y 1
np.random.rand(4,2)

array([[0.8072625 , 0.23363062],
       [0.49858585, 0.32129732],
       [0.69814915, 0.19796679],
       [0.08607979, 0.99520497]])

In [9]:
# array 3D de decimales entre 0 y N
np.random.uniform(10, size=[2,2,2])

array([[[3.2717853 , 8.40546155],
        [5.09768354, 3.52839805]],

       [[1.67630333, 4.72731082],
        [2.98751362, 3.72383003]]])

In [13]:
# array 4D de decimales entre -N = -10 y M = 10
np.random.uniform(-10, 10, size=[2,2,2,2])

array([[[[-9.22262358, -6.61108861],
         [-0.2900906 ,  4.57876403]],

        [[-6.55571947,  1.34258955],
         [ 1.55874262, -6.50144914]]],


       [[[-5.97942568, -1.69863156],
         [-0.25102624,  1.96770704]],

        [[-8.09153452, -0.53646239],
         [ 7.58809548,  7.72404482]]]])

In [31]:
# número entero entre 0 y N
np.random.randint(10) # N = 10

8

In [32]:
# array de enteros entre 0 y N
np.random.randint(10, size=[3,2])

array([[0, 5],
       [8, 3],
       [5, 4]])

In [33]:
# array de enteros entre -N y M
np.random.randint(-10, 10, size=[3,2])

array([[  4, -10],
       [  5,  -7],
       [  5,   0]])

In [34]:
# array uniforme con curva gaussiana
np.random.normal(size=20)

array([ 0.01935179,  1.10243725,  0.23308549,  1.06519013,  1.05958997,
       -1.38635021, -0.3586975 , -0.34902714, -0.48859762, -0.56415332,
       -0.77280051,  1.56328367, -2.10383628, -1.42746961,  1.01076916,
       -0.1759797 , -0.65607221, -1.16045414, -0.45784317,  0.90198582])

## Permutaciones

In [35]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# desordenar un array
np.random.shuffle(arr)

arr

array([6, 7, 9, 2, 8, 1, 3, 5, 0, 4])

In [40]:
# generar secuencia permutada a partir de un número
np.random.permutation(15)

array([ 5, 11, 12,  2, 13,  8,  6,  4, 10,  9,  7,  3,  1, 14,  0])