# Filtrado de arrays

En esta lección vamos a repasar algunas funciones para filtrar arrays. Para más información sobre las funciones disponibles no olvidéis pasaros por [la documentación oficial](https://numpy.org/doc/stable/reference/index.html).

## Filtro unique

Devuelve un array de una dimensión borrando todos los elementos duplicados:

In [1]:
import numpy as np

In [2]:
# generamos un array con números aleatorios repetidos
arr = np.random.randint(0, 10, 40)

In [3]:
arr

array([4, 3, 7, 3, 9, 9, 6, 0, 6, 1, 5, 7, 1, 6, 6, 6, 4, 3, 2, 7, 0, 3,
       5, 3, 7, 4, 4, 8, 2, 5, 7, 9, 5, 0, 5, 6, 4, 5, 4, 0])

In [4]:
# aplicamos el filtro unique
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Filtro in1d

Devuelve un array de una dimensión indicando si los elementos de una lista se encuentran en otro array:

In [5]:
np.in1d([-1, 4, 8, 12], arr)

array([False,  True,  True, False])

## Filtro where

Sirve para generar un array filtrado a partir de una condición y un valor por defecto:

In [6]:
# generamos un array con números aleatorios
arr_1 = np.random.uniform(-5, 5, size=[3,2])

arr_1

array([[ 3.89398257, -2.48425098],
       [-0.59830489, -3.1882888 ],
       [-4.18216434, -0.8717985 ]])

In [9]:
# creamos un filtro que establece los negativos a 0
arr_2 = np.where(arr_1<0, False, arr_1)

arr_2

array([[3.89398257, 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ]])

In [10]:
# añadimos otro filtro que establece los positivos a 1
arr_2 = np.where(arr_2>0, True, arr_2)

arr_2

array([[1., 0.],
       [0., 0.],
       [0., 0.]])

## Filtros booleanos

Permiten hacer comprobaciones lógicas en los arrays de booleanos:

In [11]:
# definimos un array de booleanos
arr_bool = np.array([True,True,True,False])

In [12]:
# comprobar si todos los elementos del array son True
arr_bool.all()

False

In [13]:
# comprobar si al menos un elementos del array es True
arr_bool.any()

True

También funciona con múltiples dimensiones pasando el eje:

In [14]:
# definimos un array de booleanos 2d
arr_bool_2d = np.array(
    [
        [False, True],
        [False, True],
        [False, True]
    ]
)

arr_bool_2d

array([[False,  True],
       [False,  True],
       [False,  True]])

In [15]:
# comprobar si alguna de las columnas es todo True
arr_bool_2d.all(0)

array([False,  True])

In [16]:
# comprobar si alguna de las filas tiene algún True
arr_bool_2d.any(1)

array([ True,  True,  True])