# Arrays y persistencia

Por último vamos a ver algunas funciones que nos permitirán almacenar los arrays en ficheros. Vienen bien si estamos trabajando y necesitamos almacenar nuestros datos para recuperarlos en otro momento.

Veremos dos métodos, el clásico en ficheros binarios y la variante en formato de texto. Los primeros no se pueden abrir con un editor de texto para editarlos, los segundos sí. Por contra los ficheros binarios pueden almacenar varios arrays y los ficheros de texto únicamente un array por fichero, así que utilizad las dos formas dependiendo de vuestros intereses.

Para más información sobre la persistencia buscad la sección pertinente en [la documentación oficial](https://numpy.org/doc/stable/reference/routines.io.html).

## Guardado binario

In [8]:
import numpy as np

# creamos un array aleatorio
arr_1 = np.random.randint(0,4,[3,3])

arr_1

array([[3, 3, 0],
       [1, 1, 3],
       [3, 0, 2]])

In [9]:
# lo guardarmos en un binario con extensión .npy
np.save('arr_1.npy', arr_1)

El fichero se creará en el mismo directorio del script donde hemos ejecutado el comando.

In [6]:
# borramos el array de la memoria para asegurarnos de que ya no existe
del(arr_1)

arr_1

NameError: name 'arr_1' is not defined

In [10]:
# lo cargamos desde el fichero binario
arr_1 = np.load('arr_1.npy')

arr_1

array([[3, 3, 0],
       [1, 1, 3],
       [3, 0, 2]])

En ficheros binarios podemos guardar y recuperar varios arrays a la vez:

In [11]:
# creamos otro array aleatorio
arr_2 = np.random.randint(-4,0,[3,3])

arr_2

array([[-1, -3, -4],
       [-3, -3, -2],
       [-3, -1, -4]])

In [12]:
# utilizaremos savez para guardar de forma comprimida con la extensión .npz
# debemos especificar una clave para cada array que queramos guardar
np.savez('arrays.npz', arr_1=arr_1, arr_2=arr_2)

In [13]:
# los borramos de la memoria
del(arr_1)
del(arr_2)

In [14]:
# los cargamos desde el fichero binario
arrays = np.load('arrays.npz')

arrays

NpzFile 'arrays.npz' with keys: arr_1, arr_2

In [ ]:
# mediante la clave de guardado podemos recuperarlos

In [15]:
arrays['arr_1']

array([[3, 3, 0],
       [1, 1, 3],
       [3, 0, 2]])

In [16]:
arrays['arr_2']

array([[-1, -3, -4],
       [-3, -3, -2],
       [-3, -1, -4]])

## Guardado en texto

Básicamente se hace de la misma forma cambiando las funciones:

- Para guardar utilizamos `savetxt()`
- Para cargar utilizamos `loadtxt()`

In [17]:
# creamos un array de prueba
arr_3 = np.random.randint(-10,10,[3,3])

arr_3

array([[-9,  7,  3],
       [ 9, -3,  2],
       [-6, -9,  8]])

In [18]:
# lo guardamos en un fichero de texto
np.savetxt('arr_3.txt', arr_3)

Por defecto los arrays en ficheros de texto se guardan con filas separadas por saltos de línea y columnas separadas por espacios (algo así):

```
6.000000000000000000e+00 -7.000000000000000000e+00 -4.000000000000000000e+00
-5.000000000000000000e+00 -9.000000000000000000e+00 -1.000000000000000000e+00
-3.000000000000000000e+00 4.000000000000000000e+00 -5.000000000000000000e+00
```

Podemos establecer el separador a voluntad:

In [19]:
# guardamos separando las columnas con ,
np.savetxt('arr_3.txt', arr_3, delimiter=',')

Ahora sería algo así:

```
6.000000000000000000e+00,-7.000000000000000000e+00,-4.000000000000000000e+00
-5.000000000000000000e+00,-9.000000000000000000e+00,-1.000000000000000000e+00
-3.000000000000000000e+00,4.000000000000000000e+00,-5.000000000000000000e+00
```

No importa cómo lo guardemos, lo importante es que a la hora de recuperarlos indiquemos los separadores si los hemos cambiado:

In [20]:
# lo borramos de la memoria
del(arr_3)

In [21]:
# lo cargamos indicando el separador (si lo hemos cambiado)
arr_3 = np.loadtxt('arr_3.txt', delimiter=',')

arr_3

array([[-9.,  7.,  3.],
       [ 9., -3.,  2.],
       [-6., -9.,  8.]])